spring:
  application:
    name: bus-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/,http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8762}/eureka/

---
spring:
  profiles: server1

server:
  port: 8071

---
spring:
  profiles: server2

server:
  port: 8072

