server:
  port: 8887

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/,http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8762}/eureka/

spring:
  application:
    name: config-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://git.oschina.net/toopoo/config.git
#          searchPaths: /
  cloud:
      config:
        server:
          native:
          #mac
            search-locations: /Users/chan/Documents/chan/github/SpringCloud/config-store
          #windows
#            searchLocations: D:/git/springcloud/SpringCloud/config-store
  profiles:
      active:
      - native

management:
  endpoints:
    web:
      exposure:
        include: '*'